### ISSUE TITLE
Couldn't run successfully

### ISSUE THREAD

**Issue by Jbai795** [arimitx/vizard#1]
I am running the project on Linux. After all setup processes, the project can be built successfully. However, when running each module separately, for example, for the server module, in /server/target, running java -jar server-1.0.jar, there shows no communication between each module. I do not know why, could you please give me some suggestions for the possible reasons?

**Comment by arimitx** [comment]
Hi Jbai795,

For our project, you need to setup two servers for the server module. For each server, it requires an external kafka service to interact with other parties and an external mysql service as the data source. Please check you have set up the necessary services and config the properties as described in the README file of each module.

The modules interact with each other mainly through the kafka pipe. However, if you wish to try submitting some requests, you may take a look at the APIs in the controller files in each module. Thank you.

**Comment by Jbai795** [comment]
Hi, thanks for your reply. I have set up two servers, as you said, as well as the corresponding kafka service and MySQL. You may check two configurations. 
The problem is there is still no interaction between every module. 
I have checked and found that there is no content in the tables in the two databases.
What do you think is the reason?
I have very little background in Java and other dependencies. Sorry for these too many questions. 


[Archive.zip](https://github.com/user-attachments/files/19341689/Archive.zip)

**Comment by arimitx** [comment]
> Could you please check if this is similar to yours?

Yes.

> The problem is there is still no interaction between every module.

I would suggest you to use some debugging tools to look up the contents inside kafka brokers, i.e. https://github.com/dushixiang/kafka-map

> I have checked and found that there is no content in the tables in the two databases.

The provided db file is just a skeleton of the DB, you need to create mock data by your self.

Moreover, I will attach a docker compose config here which I used when developing the vizard. Maybe this is helpful to you.

```
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{your listener host}:{port}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: {db root password}
      TZ: {your timezone}
      MYSQL_DATABASE: vizard-db
      MYSQL_USER: vizard
      MYSQL_PASSWORD: vizard123
```
